// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hecmeqflwveyqkemkioz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlY21lcWZsd3ZleXFrZW1raW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NzI0OTcsImV4cCI6MjA1NTI0ODQ5N30.8ChG18zherOjhzFVFT6FrcB0EWqFCJD11mYSabBpJwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);